name: Build Release

env:
  SMART_CONTRACT_NAME: new.chat

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ubuntu-1804-build:
    name: Ubuntu 18.04 | Build
    runs-on: ubuntu-18.04
    timeout-minutes: 15
    container: 
      image: avm007/eosio.cdt:latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2   

      - name: Build Release
        run: |
          chmod +x build.sh
          ./build.sh -e /root/eosio/2.0 -c /usr/opt/eosio.cdt

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ubuntu-1804-build-release
          path: |
            build/Release/*/*.abi
            build/Release/*/*.wasm
